services:
  - type: web
    name: empaquetado-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_KEY
        sync: false
      - key: CORS_ORIGIN
        sync: false
