import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const testDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(testDir, '..');
const indexSource = fs.readFileSync(path.join(repoRoot, 'src', 'index.js'), 'utf8');
const migrationSource = fs.readFileSync(path.join(repoRoot, 'scripts', 'migration-solicitudes-sedes-outbox.sql'), 'utf8');
const appsScriptSource = fs.readFileSync(path.join(repoRoot, 'scripts', 'google_apps_script_solicitudes_sedes.gs'), 'utf8');

test('solicitudes sedes centralizes permissions with existing roles', () => {
  assert.match(indexSource, /const SOLICITUDES_SEDES_PERMISSIONS = Object\.freeze/);
  assert.match(indexSource, /solicitudCreate:\s*\[APP_ROLES\.ADMIN,\s*APP_ROLES\.PRODUCCION\]/);
  assert.match(indexSource, /entregaCreate:\s*\[APP_ROLES\.ADMIN,\s*APP_ROLES\.ALMACEN\]/);
  assert.match(indexSource, /productUnitUpdate:\s*\[APP_ROLES\.ADMIN,\s*APP_ROLES\.ALMACEN\]/);
});

test('allowed units include configured initial list and normalize LTS to LT', () => {
  assert.match(indexSource, /UND,KG,PAQ,LT,CAJ,BLT,ENV,SAC,RLL,BOLSA,CESTA,BULTO/);
  assert.match(indexSource, /clean === 'LTS' \? 'LT' : clean/);
});

test('request handlers use auth guard, transactions, rollback and response contract', () => {
  assert.match(indexSource, /requireRolesForRequest\(req, res, SOLICITUDES_SEDES_PERMISSIONS\.solicitudCreate\)/);
  assert.match(indexSource, /requireRolesForRequest\(req, res, SOLICITUDES_SEDES_PERMISSIONS\.entregaCreate\)/);
  assert.match(indexSource, /await client\.query\('BEGIN'\)/);
  assert.match(indexSource, /await client\.query\('COMMIT'\)/);
  assert.match(indexSource, /await client\.query\('ROLLBACK'\)/);
  assert.match(indexSource, /json\(\{ ok: true/);
  assert.match(indexSource, /json\(\{ ok: false, error:/);
});

test('linked deliveries lock solicitud and reject cancelled or completed records', () => {
  assert.match(indexSource, /FOR UPDATE/);
  assert.match(indexSource, /estadoSolicitud === 'CANCELADA'/);
  assert.match(indexSource, /estadoSolicitud === 'COMPLETADA'/);
  assert.match(indexSource, /Math\.max\(0, solicitada - entregada\)/);
});

test('sheets outbox is transactional and retry-safe', () => {
  assert.match(indexSource, /createSolicitudesSheetsOutboxEvent\(client, 'solicitud'/);
  assert.match(indexSource, /createSolicitudesSheetsOutboxEvent\(client, 'entrega'/);
  assert.match(indexSource, /FOR UPDATE SKIP LOCKED/);
  assert.match(indexSource, /estado = 'procesando'/);
  assert.match(indexSource, /markSolicitudesSheetsOutbox/);
});

test('outbox migration only creates technical sync infrastructure', () => {
  assert.match(migrationSource, /CREATE TABLE IF NOT EXISTS public\.solicitudes_sedes_sheets_outbox/);
  assert.match(migrationSource, /id_sync BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/);
  assert.match(migrationSource, /synced_at TIMESTAMP WITH TIME ZONE/);
  assert.match(migrationSource, /created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW\(\)/);
  assert.match(migrationSource, /updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW\(\)/);
  assert.match(migrationSource, /UNIQUE \(event_type, referencia_externa\)/);
  assert.match(migrationSource, /WHERE estado IN \('pendiente', 'error'\)/);
  assert.doesNotMatch(migrationSource, /ALTER TABLE solicitudes_sedes/i);
  assert.doesNotMatch(migrationSource, /DROP TABLE/i);
});

test('apps script uses secret validation, lock service and idempotent row reference', () => {
  assert.match(appsScriptSource, /LockService\.getScriptLock/);
  assert.match(appsScriptSource, /SOLICITUDES_SHEETS_WEBHOOK_SECRET/);
  assert.match(appsScriptSource, /SOLICITUDES_SPREADSHEET_ID/);
  assert.match(appsScriptSource, /row_reference/);
  assert.match(appsScriptSource, /buildExistingReferences_/);
});

test('historical importer defaults to dry-run and reports rejected rows', () => {
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'solicitudes-sedes-'));
  const csvPath = path.join(tmpDir, 'historico.csv');
  fs.writeFileSync(csvPath, [
    'tipo,fecha,sede,codigo_producto,cantidad,unidad,solicitud_id',
    'solicitud,2026-08-03,SL,PTEM0051,10,UND,',
    'entrega,03/08/2026,SL,PTEM0051,5,LTS,',
    'solicitud,31/02/2026,SL,PTEM0051,0,XYZ,',
  ].join('\n'));

  const output = execFileSync(process.execPath, [
    path.join(repoRoot, 'scripts', 'import-solicitudes-sedes-historico.js'),
    '--file',
    csvPath,
  ], { encoding: 'utf8' });
  const parsed = JSON.parse(output);
  assert.equal(parsed.mode, 'dry-run');
  assert.equal(parsed.total_rows, 3);
  assert.equal(parsed.accepted, 2);
  assert.equal(parsed.rejected.length, 1);
});
