-- Infraestructura para Ventas Diarias y Prediccion de Demanda.
-- Preparado para aplicar manualmente en SPanel/phpPgAdmin.
-- NO ejecutado por la aplicacion.
--
-- Las tablas ventas_diarias y predicciones_demanda ya existen segun schemas.sql.
-- Los CREATE TABLE IF NOT EXISTS son solo una red de seguridad para entornos
-- donde el dump no se haya aplicado por completo.

CREATE TABLE IF NOT EXISTS public.ventas_diarias (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha DATE NOT NULL,
  sede_id INTEGER NOT NULL,
  producto_id INTEGER NOT NULL,
  cantidad INTEGER NOT NULL,
  precio_unitario NUMERIC(10,2) NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  CONSTRAINT uq_ventas_diarias_fecha_sede_producto UNIQUE (fecha, sede_id, producto_id),
  CONSTRAINT fk_ventas_diarias_sede FOREIGN KEY (sede_id) REFERENCES public.sedes(id_sede),
  CONSTRAINT fk_ventas_diarias_producto FOREIGN KEY (producto_id) REFERENCES public.productos(id_producto)
);

CREATE INDEX IF NOT EXISTS ix_ventas_diarias_fecha
  ON public.ventas_diarias (fecha);
CREATE INDEX IF NOT EXISTS ix_ventas_diarias_sede
  ON public.ventas_diarias (sede_id);
CREATE INDEX IF NOT EXISTS ix_ventas_diarias_producto
  ON public.ventas_diarias (producto_id);

CREATE TABLE IF NOT EXISTS public.predicciones_demanda (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_objetivo DATE NOT NULL,
  sede_id INTEGER NOT NULL,
  producto_id INTEGER NOT NULL,
  cantidad_proyectada NUMERIC(10,2) NOT NULL,
  fecha_calculo TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
  version_modelo VARCHAR(50) DEFAULT 'v1.0',
  CONSTRAINT uq_predicciones_fecha_sede_producto UNIQUE (fecha_objetivo, sede_id, producto_id),
  CONSTRAINT fk_predicciones_sede FOREIGN KEY (sede_id) REFERENCES public.sedes(id_sede),
  CONSTRAINT fk_predicciones_producto FOREIGN KEY (producto_id) REFERENCES public.productos(id_producto)
);

CREATE INDEX IF NOT EXISTS ix_predicciones_fecha_objetivo
  ON public.predicciones_demanda (fecha_objetivo);
CREATE INDEX IF NOT EXISTS ix_predicciones_sede_id
  ON public.predicciones_demanda (sede_id);
CREATE INDEX IF NOT EXISTS ix_predicciones_producto_id
  ON public.predicciones_demanda (producto_id);

-- Permitir tipo 'prediccion' en el outbox de Sheets existente
-- (sin crear tablas nuevas; se reutiliza solicitudes_sedes_sheets_outbox).
ALTER TABLE public.solicitudes_sedes_sheets_outbox
  DROP CONSTRAINT IF EXISTS chk_solicitudes_sheets_outbox_tipo;

ALTER TABLE public.solicitudes_sedes_sheets_outbox
  ADD CONSTRAINT chk_solicitudes_sheets_outbox_tipo
  CHECK (tipo IN ('solicitud', 'entrega', 'prediccion'));
