-- Infraestructura tecnica para sincronizar Solicitudes/Entregas a Sedes con Google Sheets.
-- Preparado para aplicar manualmente en SPanel/phpPgAdmin.
-- NO ejecutado por la aplicacion.
--
-- Este script no borra, recrea ni modifica las tablas de negocio:
-- solicitudes_sedes, solicitudes_sedes_detalle, entregas_sedes, entregas_sedes_detalle.

CREATE TABLE IF NOT EXISTS public.solicitudes_sedes_sheets_outbox (
  id_sync BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type VARCHAR(60) NOT NULL,
  entity_type VARCHAR(60) NOT NULL,
  entity_id BIGINT,
  tipo VARCHAR(30) NOT NULL CHECK (tipo IN ('solicitud', 'entrega')),
  referencia_externa VARCHAR(80) NOT NULL,
  payload JSONB NOT NULL,
  estado VARCHAR(30) NOT NULL DEFAULT 'pendiente'
    CHECK (estado IN ('pendiente', 'procesando', 'sincronizado', 'error')),
  intentos INT NOT NULL DEFAULT 0,
  ultimo_error TEXT,
  synced_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_solicitudes_sedes_sheets_outbox_event
    UNIQUE (event_type, referencia_externa)
);

CREATE INDEX IF NOT EXISTS idx_solicitudes_sedes_sheets_outbox_pending
ON public.solicitudes_sedes_sheets_outbox (estado, updated_at, id_sync)
WHERE estado IN ('pendiente', 'error');

CREATE INDEX IF NOT EXISTS idx_solicitudes_sedes_sheets_outbox_entity
ON public.solicitudes_sedes_sheets_outbox (entity_type, entity_id);
